### ISSUE TITLE
this.cursors in body

### ISSUE THREAD

**Issue by RassaLibre** [badsyntax/react-seed#10]
Hi,
sorry for maybe a stupid question. I really like this dev-stack which does not happen very often. I am kinda new to Flux I would prefer Baobab to be honest but Flux is also find with me. I just do not understand the following:

    this.cursors = {
      items: ['items'],
    };
    this.state = this.cursors;

It is in the body component. Can you just explain why are you appending this to the state and what it is good for? I know the principle of cursors when you have one giant state like with Baobab but I am kinda confused about what it actually does here. Thanks!

**Comment by badsyntax** [comment]
I'm not doing this at all, that code does not exist within this repo. Personally i think that's a really bad idea, state should be immutable.

**Comment by RassaLibre** [comment]
Oh! I am sorry that was just some leftover from when I was messing around with the code. I am taking this back.

**Comment by badsyntax** [comment]
Np! :)
