### ISSUE TITLE
WebSockets and JSON loader

### ISSUE THREAD

**Issue by RassaLibre** [badsyntax/react-seed#12]
Hi,
I am trying to use this stack (btw. I love it!) with WebSockets. I am not really a Webpack specialist but I am getting:

	ERROR in ./~/websocket/package.json
	Module parse failed: /Users/tomasprochazka/Documents/Searis/ReactMapBox/	node_modules/websocket/package.json Line 2: Unexpected token :
	You may need an appropriate loader to handle this file type.
	
I read online that it has something to do with loaders, so I went to the Webpack homepage, read a bit about the loaders and removed `exclude: /node_modules/,` from loaders.js under `test: /\.json$/,` and it works. The only problem is that I have no idea what I have done and if it is smart. What do you think?

**Comment by eriben** [comment]
what command did you use to generate this error?

**Comment by RassaLibre** [comment]
Ok, so this does not seem to be a solution because the whole Webpack just went bananas. First I installed the websockets:

        npm install websocket --save

and then just simply:

        npm start

**Comment by eriben** [comment]
why do you want websockets?

**Comment by eriben** [comment]
websockets are just used for livereload during development. I don't think you should install it individually from the webpack.

**Comment by RassaLibre** [comment]
Because part of the project I am working on is a real-time communication with a server and we are using websockets to achieve this.

**Comment by badsyntax** [comment]
It seems you're getting that loader error as a result of `require()`'ing something. Can you paste the code you're using to generate that error. I need to be able to replicate the error, simply installing the `websocket` lib has no effect on the webpack build.

**Comment by RassaLibre** [comment]
import WebSocket from 'websocket';

    export default {

      connectAndListen: function(){
        var socket = io(WEBSOCKET_URL);
        console.log('I am totally initing the socket!');
      }
    };

I hacked one of the files in the Websocket package which requires the package.json just to return the version. I changed it so it returns static string and it worked. But yeah, that is not a proper solution.

**Comment by RassaLibre** [comment]
Once you import it, it does the error.

**Comment by badsyntax** [comment]
The problem is you're require()ing a module that is only nodejs compatible, and is not intended to be executed in the browser. The webpack config in this repo expects webpack to be used [for the browser](https://github.com/badsyntax/react-seed/blob/b995d8f0e1458a0e37763aa95a5fe415ec3975b3/webpack/config.js#L33).

**Comment by RassaLibre** [comment]
I see. Hmmm... Any suggestions? I can not find anything when I google 'Webpack websockets'.

**Comment by badsyntax** [comment]
Use the websocket lib for your server (which doesn't use the webpack build) and then use some browser websocket lib for your client app which does use the webpack build.

**Comment by RassaLibre** [comment]
The server is completely written in Go so that should not be a problem, but finding a websockets browser lib with webpack seems quite difficult. Well, that is my problem. Anyway, thanks! I will see what I can find on npm.

**Comment by badsyntax** [comment]
It might be easiest to just use the native API. You can use a library like https://github.com/gimite/web-socket-js to provide a flash fallback for older browsers, unfortunately it doesn't appear to be on npm.

**Comment by RassaLibre** [comment]
Yeah, I was actually checking the native API and it does not look extra difficult. I will probably try that first and then the library you have sent me. But thanks, this was helpful! :)
