### ISSUE TITLE
Removing material-ui-sass

### ISSUE THREAD

**Issue by chiefGui** [badsyntax/react-seed#13]
According to https://github.com/gpbl/material-ui-sass#material-ui-sass-discontinued, seems like it was discontinued. What's then?

**Comment by badsyntax** [comment]
I'd like to incorporate the css-loader's [css modules](https://github.com/webpack/css-loader#css-modules), using material-ui's inline styles.

**Comment by chiefGui** [comment]
Thanks!

**Comment by badsyntax** [comment]
material-ui-sass has been removed and this seed is now working with inline styles. Have a look in the https://github.com/badsyntax/react-seed/tree/feature/material-ui branch.

**Comment by badsyntax** [comment]
To clarify, the project is now using local css via css-modules: https://github.com/css-modules/css-modules

It's still using Sass as a pre-processor, but the processed css is managed via css modules. 

The latest version of material-ui is using inline-styles (managed with JS I believe), which is a slightly different approach but as far as I can tell does not conflict with local css. 

Let me know if there are any probs. Close this issue if you are happy with the new approach.

**Comment by chiefGui** [comment]
:+1:
