### ISSUE TITLE
Stylesheet is missing

### ISSUE THREAD

**Issue by dcorral** [badsyntax/react-seed#14]
When I run "npm run build", the link to the app.version.css is missing in build/index.html.
To fix it, remove quotes from 'false' because debug is not a string.

https://github.com/badsyntax/react-seed/blob/master/app/index.html#L7

**Comment by badsyntax** [comment]
Are you sure? 'debug' is a string, because it's passed as a string: https://github.com/badsyntax/react-seed/blob/f6cbd0378413840c11d1ea9688126640b0791ad0/webpack/loaders.js#L19 (Not ideal, I know).

This is the output I'm getting in `index.html` when I run `npm run build`:

```html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>react-seed</title>
  
  <link type="text/css" rel="stylesheet" media="all" href="css/app.0.0.13.css" />
  
</head>
<body>
  <div id="app"></div>
  <script src="js/app.0.0.13.js"></script>
</body>
</html>
```

**Comment by dcorral** [comment]
**Input**: app/index.html

```
<body>
  <div>The type of 'version' variable is <%= typeof(version) %></div>\n
  <div>The type of 'title' variable is <%= typeof(title) %></div>
  <div>The type of 'debug' variable is <%= typeof(debug) %></div>
  ...
</body>
```

**Output**: build/index.html

```
<body>
  <div>The type of 'version' variable is string</div>
  <div>The type of 'title' variable is string</div>
  <div>The type of 'debug' variable is boolean</div>
  ...
</body>
```
I found out why. I started react-seed from a fresh install of node_modules so I use the last version of "loader-utils" package. (https://github.com/webpack/loader-utils/commit/1c75aac162e77351442bcc05e186959315abcea3 and https://github.com/webpack/loader-utils/commit/63f19e9a0772292c1cb1e48944cbc3294317fd3f)

"true" and "false" strings are converted to boolean since loader-utils@0.2.9.

<pre>
template-html-loader@0.0.3 /tmp/react-seed/node_modules/template-html-loader
├── consolidate@0.10.0
└── loader-utils@<b>0.2.10</b>
</pre>

What is your version of loader-utils ?

**Comment by badsyntax** [comment]
Thanks for feeding back this information! That's exactly what's happened. Dev's should be more careful about how they release, a change of behaviour should not be a patch release, as is the case here. 
I'll fix this when I have some time. Thanks again!

**Comment by badsyntax** [comment]
Or feel free to send a PR! 

I'd like to update all the packages at some point (npm-check-updates is helpful here).

**Comment by dcorral** [comment]
Thanks for the new release.
