### ISSUE TITLE
Es7 syntax error on static prop types

### ISSUE THREAD

**Issue by eguneys** [badsyntax/react-seed#16]
I am using babel es7 features and I've this class definition:
```
@DragSource(ItemTypes.STONE, stoneSource, collect)
class OkeyStone extends React.Component {
  static propTypes = {
    connectDragSource: PropTypes.func.isRequired,
    isDragging: PropTypes.bool.isRequired
  };
}
```

I get this error:

```
ERROR in ./app/components/OkeyStone/OkeyStone.js
Module build failed: SyntaxError: /home/ubuntu/webdev/learn/yuzbir-react/app/components/OkeyStone/OkeyStone.js: Unexpected token (27:19)
  25 | @DragSource(ItemTypes.STONE, stoneSource, collect)
  26 | class OkeyStone extends React.Component {
> 27 |   static propTypes = {
     |                    ^
  28 |     connectDragSource: PropTypes.func.isRequired,
  29 |     isDragging: PropTypes.bool.isRequired
  30 |   };
```

Even though I added `stage=1` option to babel loader why do I get this error?

**Comment by badsyntax** [comment]
It needs to be stage=0 as mentioned here: http://babeljs.io/docs/usage/experimental/  Stage 0 is experimental. I've added ES7 usage examples with the commit above. Might be worth updating your code with the latest changes as i added fixes for linting ES7 (code now has to be pre-lint compiled by babel)
