### ISSUE TITLE
How to import image files from scss file

### ISSUE THREAD

**Issue by eguneys** [badsyntax/react-seed#20]
If I import a png file from a js file like this:

`import 'public/image.png'` it works.

but I can't import within scss file like this:
```
.logo {
  background: url('public/image.png')
}
```
this gives me module not found error.

**Comment by badsyntax** [comment]
Please paste the full error.

**Comment by eguneys** [comment]
```
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader?outputStyle=expanded&includePaths[]=/home/ubuntu/webdev/learn/react-facebook-pt/app/scss&includePaths[]=/home/ubuntu/webdev/learn/react-facebook-pt/node_modules&sourceMap&sourceMapContents=true!./app/components/PokerLobby/_PokerLobby.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./public/poker/main_screen/logo.png in /home/ubuntu/webdev/learn/react-facebook-pt/app/components/PokerLobby
 @ ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader?outputStyle=expanded&includePaths[]=/home/ubuntu/webdev/learn/react-facebook-pt/app/scss&includePaths[]=/home/ubuntu/webdev/learn/react-facebook-pt/node_modules&sourceMap&sourceMapContents=true!./app/components/PokerLobby/_PokerLobby.scss 6:106-152
```

I am not using local styles, this commit https://github.com/badsyntax/react-seed/commit/740488328cb785d870b742f659a707c102870af2.

**Comment by eguneys** [comment]
Also this works: https://github.com/webpack/style-loader/issues/55

**Comment by badsyntax** [comment]
It shouldn't matter if you're using local styles or not, the resulting css should be processed by the style-loader regardless of how you generate the css.
What is the publicPath you set? Based on my own experience, and based on the comments in that issue, it has to be absolute. When I had this issue in the past, I could not figure out if webpack supports "relative" publicPate, I don't think it does.
