### ISSUE TITLE
SASS and source maps

### ISSUE THREAD

**Issue by gryzzly** [badsyntax/react-seed#3]
Hey, I'm trying to figure out source maps for SASS and it doesn't seem to work with the config provided (although clearly there's an intention):
```js
  {
    test: /\.scss$/,
    loader: cssExtractTextPlugin.extract('style-loader', [
      'css-loader?sourceMap',
      'postcss-loader',
      'sass-loader?' + [
        'sourceMap',
        'outputStyle=expanded',
        'includePaths[]=' + path.resolve(__dirname, './app/scss'),
        'includePaths[]=' + path.resolve(__dirname, './node_modules')
      ].join('&')
    ].join('!'))
  }
```

Did you ever get it working? 

Thanks!

**Comment by badsyntax** [comment]
I'm seeing sourcemaps working, I think you need to explicitly enable this in chrome:

![screen shot 2015-04-15 at 22 07 31](https://cloud.githubusercontent.com/assets/102141/7169286/f7d2285a-e3bb-11e4-9b45-0f80d317d9a9.png)

**Comment by gryzzly** [comment]
@badsyntax thanks for the prompt reply. 

With this repo cloned and only the following diff (as otherwise there's eslint and syntax errors): 

```diff
[13:55:21] ~/Source/react-seed (master*)$ git diff
diff --git a/app/stores/SelectedStore.js b/app/stores/SelectedStore.js
index 54b0db9..a0f0f10 100644
--- a/app/stores/SelectedStore.js
+++ b/app/stores/SelectedStore.js
@@ -6,7 +6,8 @@ import AppDispatcher from '../dispatcher/AppDispatcher';
 import {
   SELECTED_UPDATED,
   ITEM_SELECTED,
-  ITEM_DESELECTED
+  ITEM_DESELECTED,
+  ITEMS_UPDATED
 } from '../constants/AppConstants';
 
 class SelectedStore extends BaseStore {
```

I tried both stable `Version 41.0.2272.104 (64-bit)` and Canary `Version 44.0.2371.0 canary (64-bit)` Chromes and Firefox `37.0.1` with the same result: 
![screen shot 2015-04-16 at 1 58 57 pm](https://cloud.githubusercontent.com/assets/26131/7179468/d2d76418-e440-11e4-9d99-1d56fab8b7da.png)

![screen shot 2015-04-16 at 1 54 19 pm](https://cloud.githubusercontent.com/assets/26131/7179470/dabd794c-e440-11e4-834f-2a8497a2a7a0.png)

It doesn't seem that `//# sourceMap` is there at all. Is it definitely the same branch and the same code we are running? 

Thanks!

**Comment by badsyntax** [comment]
That's odd. Yea this needs to be resolved.

Even in my example, it will show you the line numbers in the original file in the devtools, but when you click on the file in the dev tools it opens up the compiled css instead of the sass file which is not correct.

Will work on this this evening or over the weekend. Thanks for letting me know!

**Comment by gryzzly** [comment]
I'm also digging into it, but after I resolve some other issues, will let you know if I have progress.

**Comment by badsyntax** [comment]
Have tracked the problem down to the postcss-loader, see: https://github.com/postcss/postcss-loader/pull/5

**Comment by badsyntax** [comment]
I'll add a fix to this repo as soon as a new `postcss-loader` version has been been released.

**Comment by badsyntax** [comment]
Ok this is fixed now in master!
