### ISSUE TITLE
css replacement not working

### ISSUE THREAD

**Issue by mxaly** [badsyntax/react-seed#9]
Need to refresh page to see style chagnes.

**Comment by badsyntax** [comment]
Are you using the latest version of the code? CSS reload should be working without refreshing page.

**Comment by badsyntax** [comment]
On OSX, it seems you need to interact with the browser in some way for the styles to be updated. For me, it's as simple and having the browser window focused and then moving the mouse over the window.

**Comment by mxaly** [comment]
i'm using osx too with chrome 42.0.2311.152 (64-bit)
It's latest version + I updated all css related packages to latest version - it's not helping.

Chrome console log: 
```
client?ad37:65 [WDS] App hot update...
only-dev-server.js:62 [HMR] Checking for updates on the server...
log-apply-result.js:11 [HMR] The following modules couldn't be hot updated: (They would need a full reload!)
log-apply-result.js:13 [HMR]  - 259
log-apply-result.js:18 [HMR] Nothing hot updated.
only-dev-server.js:48 [HMR] App is up to date.
```

full node log: https://gist.github.com/mxaly/1aeadbc0f58b507f98b7

**Comment by badsyntax** [comment]
See this line: https://gist.github.com/mxaly/1aeadbc0f58b507f98b7#file-react-seed-css-issue-node-log-L426

You're not going to get css livereload if you're bundling the css. Have you made any changes to the `webpack.config.js` or npm scripts?

**Comment by mxaly** [comment]
just added altJs to package - should not be related
also just now i generated project one more time - same problem there

**Comment by badsyntax** [comment]
Ok thanks for letting me know, i'll look into it.

**Comment by mxaly** [comment]
thanks :)

**Comment by mxaly** [comment]
looks like it's fixed in last version. Closing
